# Generated by Django 2.1.1 on 2018-11-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='sub_name',
            field=models.CharField(default='deafult', max_length=200),
        ),
        migrations.AddField(
            model_name='userdata',
            name='sub_report_old',
            field=models.CharField(default='deafult', max_length=200),
        ),
    ]
