# Generated by Django 2.1.1 on 2018-11-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0005_userdata_recent_push'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='old_reports',
            field=models.CharField(default='null', max_length=500),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='recent_push',
            field=models.CharField(default='[]', max_length=200),
        ),
    ]
